Repository bounswe/bounswe2018group9, pull requests merged in 2018-12, with the labels that each got.

#355 fix(interfaces): make fields of user optional
  frontend/src/app/interfaces/user.interface.ts
Labels: Type: Bug

#356 Build CI Task
  .circleci/config.yml
  scripts/deploy.sh
Labels: Platform: Devops

#363 Fix CI & CD
  .circleci/config.yml
  scripts/deploy.sh
Labels: Type: Bug

#375 Quick Fix
  backend/controllers/EventController.js
Labels: Type: Bug

#377 fix(ion-item): make borders transparent
  frontend/src/global.scss
Labels: Platform: Frontend, Type: Bug
